Decorators
st119018/spbu-python-course pull request #2
Opened 2024-10-14 18:50 UTC by st119018

- [x] Частичное применение (каррирование, curry) --- это превращение функции от нескольких параметров в функцию от одного параметра, возвращающую функцию от остальных параметров. К ней существует обратная операция --- uncarry.
В Python каррирование в таком виде затруднено из-за произвольной арности. Напишите функцию `curry_explicit(function, arity)` и парную к ней `uncurry_explicit(function, arity)`.
- Требования/допущения:
  - [x] Если пользователь ошибся при указании арности, то бросить исключение.
  Можно [здесь](https://docs.python.org/3/tutorial/errors.html) посмотреть что это и как с этим работать.
  Здесь имеется в виду отслеживание простых ситуаций вида: пользователь указал, что функция от 1 аргумента,
  а передает 5 или же передает аргументы и указывает, что арность --- ноль.
  НЕ требуется проверки, действительно ли передана функция от трех аргументов, если передали арность = 3.
  - [x] Отрицательная арность невозможна --- бросить исключение
  - [x] При арности 0 результатом будет функция от 0 параметров: `curry_explicit(f,0)() == f()`
  - [x] При арности 1 --- функция от 1 параметра: `curry_explicit(f,1)(x) == f(x)`
  - [x] Не забудьте, что есть произвольно-арные функции, такие как print(); curry_explicit должна замораживать их арность,
  т.е. нельзя написать `curry_explicit(print,2)(1)(2)(3,4,5)`. В данном случае `curry_explicit(print,2)(1)(2)` вернет `None`, что сделает невозможным дальнейшее применение (Python сам бросит ошибку, данный кейс отдельно обрабатывать не нужно)
  - [x] Именованные аргументы поддерживать не нужно
-----
- [x] Реализовать декоратор для кеширования результатов выполнения функции.
То есть необходимо сохранять результаты вычислений для разного набора аргументов функции.
Аргумент декоратора – сколько последних результатов хранить.
По умолчанию ничего не кэшируется. Необходимо поддержать как неименованные аргументы, так и именованные.
-----
- [x] Напишите декоратор `@smart_args`, который анализирует типы значений по умолчанию аргументов функции и,
в зависимости от этого, копирует и/или вычисляет их перед выполнением функции:
  - `Evaluated(func_without_args)` --- подставляет значение по умолчанию, вычисляемое в момент вызова.
  В качестве аргумента принимает функцию БЕЗ аргументов, которая что-то возвращает.
  Например, она может менять глобальный счетчик или что-то считать внутри класса.
  Во время работы необходимо вызвать эту функцию и использовать значение, которое будет получено в результате выполнения.
  - `Isolated()` --- это фиктивное значение по умолчанию; аргумент должен быть передан, но в момент передачи - скопирован (глубокая копия).
  - Также необходимо реализовать сами `Evaluated` и `Isolated`.
- Требования\допущения:
  - [x] Необходима поддержка только именованных аргументов
  - [x] Не нужно сочетать `Isolated` и `Evaluated`
  - [x] Добавьте проверки (assert) того, что пользователь случайно не вышел за эти рамки
  (использует `Isolated` и `Evaluated` в сочетании или пытается их использовать для позиционных аргументов)
- [ ] **(Доп., +5 баллов)** Добавить поддержку позиционных аргументов (необходимо разобраться с `inspect.getfullargspec()`).
В таком случае необходимо добавить настройку для декоратора - возможность отключить данную функциональность.

2024-10-15 11:38 UTC, Krekep requested changes
Необходимо расширить тесты

2024-10-15 11:38 UTC, Krekep commented on tests/test_curry.py
Не хватает теста проверяющего, что каррирование "замораживает" арность функции с произвольным числом аргументов

2024-10-15 20:32 UTC, golkaem commented on tests/test_curry.py
Изменила тесты
Заменила функцию print на max, теперь в тестах проверяется, что с количеством аргументов, равным данной арности, функция работает верно, но при попытке подать больше аргументов происходит ошибка

2024-10-19 08:28 UTC, Krekep approved these changes
Зачтено

2024-10-22 16:59 UTC, merged