Шагимарданова. Task№3
st119018/spbu-python-course pull request #3
Opened 2024-10-14 18:55 UTC by st119018

- [x] Написать генераторное выражение для четырехмерного набора векторов [RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
- [x] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
- [x] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

2024-10-15 11:50 UTC, Krekep requested changes
Необходимы исправления.
Также, слейте ветку первого задания с `main`, чтобы потом не тянуть в каждую ветку изменения из всех заданий до текущего

2024-10-15 11:50 UTC, Krekep commented on project/rgba.py
> +                        yield (r, g, b, a)
Это функция-генератор, а не генераторное выражение.
Подразумевалось что-то в духе
```
x = [i for i in range(10)]
```

2024-10-15 11:50 UTC, Krekep commented on tests/test_prime.py
Не хватает теста, в котором несколько раз подряд вызывается функция получения k-го простого числа

2024-10-15 11:50 UTC, Krekep commented on tests/test_prime.py
> +        pass
Зачем оборачивать в декоратор `get_prime` эту функцию?

2024-10-15 11:50 UTC, Krekep commented on project/prime.py
> +        gen = prime_generator()
Зачем каждый раз создавать переменную `gen`? С учётом того, что `k` на вход мы по условию подаём в неубывающем порядке, то можно написать более оптимальное решение

2024-10-15 20:09 UTC, st119018 commented on project/rgba.py
> +                        yield (r, g, b, a)
Переписала как генераторное выражение

2024-10-15 20:10 UTC, st119018 commented on tests/test_prime.py
Добавила

2024-10-15 20:17 UTC, st119018 commented on tests/test_prime.py
> +        pass
Ошибка
Исправила,  теперь декоратор вызывается перед функцией, возвращающей генератор простых чисел

2024-10-15 20:19 UTC, st119018 commented on project/prime.py
> +        gen = prime_generator()
Ошибка
Исправила, теперь переменная gen создается только один раз во время вызова декоратора

2024-10-17 09:56 UTC, Krekep commented on tests/test_prime.py
У Вас сейчас есть тест на некорректный вызов этой функции несколько раз (когда вы индексы передаëте в убывающем порядке).
Добавьте тест на корректный вызов, к примеру
```
gen(1) #2
gen(1) #2
gen(5) #11
```

2024-10-17 15:02 UTC, st119018 commented on tests/test_prime.py
Переписала тесты
Теперь функция gen создаётся один раз для каждого теста и вызывается несколько раз подряд с корректными входными данными

2024-10-19 08:29 UTC, Krekep approved these changes
Зачтено

2024-10-22 16:54 UTC, merged