Шагимарданова Task№5
st119018/spbu-python-course pull request #5
Opened 2024-10-30 13:03 UTC by st119018

# Задача 5. Игра

* **Дедлайн**: 31.10.2024, 23:59
* Полный балл: 13

## Задача

- [x] Реализовать одну из игр в списке ниже. Вариант определяется как длина Вашего ФИО по модулю 2 плюс 1
  1. рулетка
  2. блэкджек
- Выбора варианта:
  - len(Шагимарданова Элина Галиевна) = 13 + 5 + 8 = 26
  - 22 % 2 = 0
  - 0 + 1 = 1 -> вариант 1
-------------------
  - Требования:
    - [x] Должно быть как минимум три различных стратегии игры ботов
    - [x] Должны быть методы, показывающие текущее состояние игры
    - [x] На каждую сущность должен быть свой класс
  - Ограничения:
    - Игра ведётся либо до победы одного/нескольких участников, либо до заданного количества шагов
  - Допущения:
    - Реализовывать Игрока необязательно. Достаточно того, что в игре будут участвовать только боты
    - Графический интерфейс необязателен. Информацию достаточно выводить в консоль
  - Проверка:
    - Будет проверяться декомпозиция на классы
    - Тесты должны отображать
      - Что состояние игры меняется с течением времени
      - Работоспособность методов влияющих на состояние игры
      - Может быть что-то ещё, тестов много не бывает
    - В папку `example`  добавлен пример работы игры с выводом информации о состоянии в каждом раунде. 
- [x] **(Доп., +5 балла)** Для реализованной игры  в папку `diagram` была добавлена UML диаграмма классов
- [ ] **(Доп., +5 балла)** С помощью метаклассов добавить стратегию бота и поменять правила игры (к примеру, количество полей или условия победы)

2024-11-01 07:32 UTC, Krekep requested changes
В целом хорошо, но есть два критических замечания --- видимость полей и магические константы

2024-11-01 07:32 UTC, Krekep commented on project/game/example/example.txt
> +    bot1 made a bet on 25 34 35 27 30 22 24 23 6 28 36 10 18 0 31 5 4 33 (single)
Добавьте вывод того, сколько бот поставил

2024-11-01 07:32 UTC, Krekep commented on project/game/roulette.py
> +        self.file_name = "project/game/example/example.txt"
Путь до файла лучше задать как keyword-only аргумент со значением по умолчанию

2024-11-01 07:32 UTC, Krekep commented on project/game/roulette.py
> +                if self.bots[i].last_bet.bet_type == "color":
Магические константы это [антипаттерн в программировании](https://en.wikipedia.org/wiki/Anti-pattern). У Вас в качестве магических констант выступают типы ставок и цвета (мб ещё что-то, пока не весь код просмотрел), перепишите код без них

2024-11-01 07:32 UTC, Krekep commented on project/game/wheel.py
> +                flag = not flag
В целом это тоже выглядит как магические константы. Можете рассказать --- что они значат?

2024-11-01 07:32 UTC, Krekep commented on project/game/diagram/UML_diagram.png
1. В целом видимость полей и методов у Вас везде хорошо определена, кроме класса `Roulette`. Измените в нём видимость для полей и методов
2. Если Вы делали в app.diagrams.net (по внешнему виду похоже), то там есть экспорт в изображение без сетки

2024-11-01 08:50 UTC, Krekep commented on project/game/roulette.py
> +                if self.bots[i].last_bet.bet_type == "color":
Не ту ссылку прикрепил, держите [правильную](https://en.wikipedia.org/wiki/Magic_number_(programming))

2024-11-01 13:48 UTC, st119018 commented on project/game/example/example.txt
> +    bot1 made a bet on 25 34 35 27 30 22 24 23 6 28 36 10 18 0 31 5 4 33 (single)
Добавила

2024-11-01 13:48 UTC, st119018 commented on project/game/roulette.py
> +        self.file_name = "project/game/example/example.txt"
Поменяла

2024-11-01 13:54 UTC, st119018 commented on project/game/roulette.py
> +                if self.bots[i].last_bet.bet_type == "color":
Убрала магические константы, выступающие в качестве типов ставок и цветов, а также коэффициентов выплаты при выигрыше

2024-11-01 14:12 UTC, st119018 commented on project/game/wheel.py
> +                flag = not flag
В колесе рулетки цвета всех секторов чередуются, кроме пар (10, 11), (18, 19), (28, 29) - они одинакового цвета

2024-11-01 14:12 UTC, st119018 commented on project/game/diagram/UML_diagram.png
Исправила

2024-11-02 07:36 UTC, Krekep requested changes
Всё хорошо, но для зачёта Вам надо избавиться от магических констант

2024-11-02 07:36 UTC, Krekep commented on project/game/strategy.py
> +        return Bet(numbers=bet_numbers, amount=bet_amount, bet_type="single")
Но Вы же сказали, что убрали магические константы, выступающие в роли типов ставок :(

2024-11-02 07:36 UTC, Krekep commented on project/game/strategy.py
> +        bet_color = random.choice(["red", "black"])
Это тоже магические строковые константы. 
Попробуйте использовать перечисления, к примеру
```
class ColorTypes(Enum):
  Red: str = "red"
  Black: str = "black"
```

Такие же перечисления можно использовать, чтобы заменить все магические константы

2024-11-16 07:27 UTC, st119018 commented on project/game/strategy.py
> +        return Bet(numbers=bet_numbers, amount=bet_amount, bet_type="single")
Убрала

2024-11-16 07:28 UTC, golkaem commented on project/game/strategy.py
> +        bet_color = random.choice(["red", "black"])
Заменила все константы на перечисление

2024-11-19 15:00 UTC, Krekep approved these changes
Зачтено

2024-11-19 16:42 UTC, merged